---
- name: Installing packages
  become: yes
  ansible.builtin.package:
    name: "{{ cim_image_upload_packages }}"
    state: present
    use: apt

- name: read images checksums from dib files
  ansible.builtin.command:
    argv:
      - "cat"
      - "{{ item.value }}.qcow2.sha256"
  loop: "{{ cim_ready_images | dict2items }}"
  register: cim_checksums_result
  changed_when: false

- name: define images checksums var
  ansible.builtin.set_fact:
    ready_images_checksums: "{{ ready_images_checksums| combine({
      item.item.key: item.stdout.split()[0]}) }}"
  loop: "{{ cim_checksums_result.results }}"

- include_tasks: upload.yml
  loop: "{{ cim_ready_images | dict2items }}"
  loop_control:
    loop_var: image_for_upload
